# Generated by Django 4.2.5 on 2023-09-13 04:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=40)),
                ('fam', models.CharField(max_length=40)),
                ('manzil', models.CharField(blank=True, max_length=70)),
                ('tel', models.CharField(max_length=70)),
                ('umumiy_summa', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Sotuvchi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=60)),
                ('fam', models.CharField(max_length=60)),
                ('manzil', models.CharField(max_length=60)),
                ('tel_nomer', models.CharField(max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Mahsulot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=40)),
                ('kelgan_sana', models.DateField(auto_now_add=True)),
                ('miqdor', models.PositiveSmallIntegerField()),
                ('olchov', models.CharField(max_length=20)),
                ('narx', models.PositiveIntegerField()),
                ('tolangan_summa', models.PositiveIntegerField(null=0)),
                ('sotuvchi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asosiy.sotuvchi')),
            ],
        ),
    ]
