# Generated by Django 4.2.5 on 2023-09-21 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0002_alter_mahsulot_tolangan_summa_buyurtma'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyurtma',
            name='summa',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
