# Generated by Django 4.2.5 on 2023-09-26 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0004_remove_mahsulot_tolangan_summa_buyurtma_miqdor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mahsulot',
            name='hajmi',
            field=models.CharField(blank=True, choices=[('0,5 litr ', '0.5 litr'), ('1 litr', '1 litr'), ('1,5 litr', '1,5 litr'), ('2 litr', '2 litr')], max_length=50),
        ),
        migrations.AlterField(
            model_name='buyurtma',
            name='nasiya',
            field=models.IntegerField(default=0, null=True, verbose_name='qarzi'),
        ),
    ]
