# Generated by Django 4.2.5 on 2023-09-29 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0005_mahsulot_hajmi_alter_buyurtma_nasiya'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='rasm',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='mahsulot',
            name='rasm',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='sotuvchi',
            name='rasm',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
